### PR TITLE
Added new property to allow connection errors to not be logged in pha…

### PR DESCRIPTION
**Pull request by rmc00**
…sor measurement mapper.

### CODE REVIEW

**Comment by rmc00** [comment]
For issue #6 to enable/disable connection errors in phasor measurement mapper

**Comment by StephenCWills** [comment]
It looks like you forgot to set the variable to its default value of true.

**Comment by rmc00** [comment]
Thanks! It was covered for phasor measurement mapper by the defaultvalue attribute but not for other input adapters. Appreciate your time to look it over.

**Comment by StephenCWills** [comment]
It looks good. Thanks for the contribution!

FYI, the DefaultValue attribute does not actually ensure that the value is initialized with its default. It only affects what the openPDC Manager displays as the default.

**Pull request merged**
