### PR TITLE
Removing CodeQL workflow

### PR DESCRIPTION
**Pull request by prestoncraw**
Removing the CodeQL workflow as we now have a job running in Jenkins that handles CodeQL analysis. [](https://build.gridprotectionalliance.org/job/GSF/job/CodeQL/)

### CODE REVIEW

**Comment by StephenCWills** [comment]
Can we make a `Build-Check` pipeline like the one we have for openXDA, and set up a GitHub check so we can see if a PR builds before merging?

**Comment by prestoncraw** [comment]
> Can we make a `Build-Check` pipeline like the one we have for openXDA, and set up a GitHub check so we can see if a PR builds before merging?

Yes, I will get that in there today.

**Comment by prestoncraw** [comment]
Build-Check pipeline is up now

**Review by StephenCWills — APPROVED** [review]

**Comment by StephenCWills** [comment]
It made me rebase the branch, but it didn't sign the commit. Seems like it's okay with me signing your commits.

**Pull request merged**
